using System.Text;
using CarPoolingAPI.DTO;
using CarPoolingAPI.Exceptions;
using CarPoolingAPI.Services;
using CarPoolingAPICore.Interface;
using CarPoolingAPICore.Models;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using Newtonsoft.Json;

namespace Tests_CarPoolingAPI;

[TestFixture(Category = "Authentication")]
public class AuthenticationApiTests_Login
{
    private HttpClient _client;
    private Mock<IAuthenticationService> _mockAuthenticationService;

    [SetUp]
    public virtual void Setup()
    {
        _mockAuthenticationService = new Mock<IAuthenticationService>();

        var factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder => { builder.ConfigureServices(services => { services.AddSingleton(_mockAuthenticationService.Object); }); });
        _client = factory.CreateClient();
    }

    [TearDown]
    public virtual void TearDown()
    {
        _client.Dispose();
    }

    [Test]
    public async Task LoginUser_Exist()
    {
        _mockAuthenticationService.Setup((auth) => auth.Login(It.IsAny<UserLoginDto>())).Returns(Task.FromResult(TestData.ValidAuthResponse));

        var content = new StringContent(JsonConvert.SerializeObject(TestData.ValidRegisterRequest), Encoding.UTF8, "application/json");
        var response = await _client.PostAsync($"{TestData.AUTH_REQUEST_ROOT}/login", content);

        Assert.That(response.IsSuccessStatusCode, Is.True);
    }

    [Test]
    public async Task LoginUser_ValidReturnToken()
    {
        _mockAuthenticationService.Setup((auth) => auth.Login(It.IsAny<UserLoginDto>())).Returns(Task.FromResult(TestData.ValidAuthResponse));

        var content = new StringContent(JsonConvert.SerializeObject(TestData.ValidRegisterRequest), Encoding.UTF8, "application/json");
        var response = await _client.PostAsync($"{TestData.AUTH_REQUEST_ROOT}/login", content);
        response.EnsureSuccessStatusCode();
        var responseString = await response.Content.ReadAsStringAsync();

        Assert.That(responseString, Is.Not.Null);
        Assert.That(responseString.Contains("token"), Is.True);
    }

    [Test]
    public async Task LoginUser_ValidReturnUserId()
    {
        _mockAuthenticationService.Setup((auth) => auth.Login(It.IsAny<UserLoginDto>())).Returns(Task.FromResult(TestData.ValidAuthResponse));

        var content = new StringContent(JsonConvert.SerializeObject(TestData.ValidRegisterRequest), Encoding.UTF8, "application/json");
        var response = await _client.PostAsync($"{TestData.AUTH_REQUEST_ROOT}/login", content);
        response.EnsureSuccessStatusCode();
        var responseString = await response.Content.ReadAsStringAsync();

        Assert.That(responseString, Is.Not.Null);
        Assert.That(responseString.Contains("userId"), Is.True);
    }
}

[TestFixture(Category = "Authentication")]
public class AuthenticationServicesTests_Register
{
    private Mock<ITokenService> _mockTokenService;
    private Mock<IUserService> _mockUserService;
    private AuthenticationService _authenticationService;

    [SetUp]
    public void Setup()
    {
        _mockTokenService = new Mock<ITokenService>();
        _mockUserService = new Mock<IUserService>();
        _authenticationService = new AuthenticationService(_mockTokenService.Object, _mockUserService.Object);

        _mockTokenService.Setup(token => token.GenerateToken(It.IsAny<User>())).Returns(TestData.VALID_TOKEN);
    }

    [TearDown]
    public void TearDown()
    {
        _authenticationService.Dispose();
    }

    [Test]
    public void RegisterUser_NoThrow()
    {
        Assert.DoesNotThrowAsync(async () => await _authenticationService.Register(TestData.ValidRegisterRequest));
    }

    [Test]
    public async Task RegisterUser_ValidReturnToken()
    {
        var result = await _authenticationService.Register(TestData.ValidRegisterRequest);

        Assert.That(result.Token, Is.EqualTo(TestData.VALID_TOKEN)); //Token is generated by the mocked token service
    }

    [Test]
    public void RegisterUser_ThrowWhenRegisterRequestEmpty()
    {
        Assert.ThrowsAsync<BadRequestServiceException>(async () => await _authenticationService.Register(new UserRegisterRequestDto()));
    }

    [Test]
    [TestCase(""), TestCase("%%%98489")]
    public void RegisterUser_ThrowWhenFirstNameInvalid(string value)
    {
        UserRegisterRequestDto invalid = TestData.ValidRegisterRequest;
        invalid.FirstName = value;
        Assert.ThrowsAsync<BadRequestServiceException>(async () => await _authenticationService.Register(invalid));
    }

    [Test]
    [TestCase(""), TestCase("%%%98489")]
    public void RegisterUser_ThrowWhenLastNameInvalid(string value)
    {
        UserRegisterRequestDto invalid = TestData.ValidRegisterRequest;
        invalid.LastName = value;
        Assert.ThrowsAsync<BadRequestServiceException>(async () => await _authenticationService.Register(invalid));
    }

    [Test]
    [TestCase(""), TestCase("%%%98489"), TestCase("user.zzzz")]
    public void RegisterUser_ThrowWhenEmailInvalid(string value)
    {
        UserRegisterRequestDto invalid = TestData.ValidRegisterRequest;
        invalid.Email = value;
        Assert.ThrowsAsync<BadRequestServiceException>(async () => await _authenticationService.Register(invalid));
    }

    [Test]
    [TestCase(""), TestCase("e"), TestCase("hhhhhhhhhhhhh"), TestCase("okoijdozhdoizj")]
    public void RegisterUser_ThrowWhenPasswordInvalid(string value)
    {
        UserRegisterRequestDto invalid = TestData.ValidRegisterRequest;
        invalid.Password = value;
        Assert.ThrowsAsync<BadRequestServiceException>(async () => await _authenticationService.Register(invalid));
    }

    [Test]
    public async Task RegisterUser_ValidAddUserToService()
    {
        _mockUserService.Setup(service => service.AddUser(It.IsAny<User>())).Verifiable();

        await _authenticationService.Register(TestData.ValidRegisterRequest);
        _mockUserService.Verify(service => service.AddUser(It.IsAny<User>()), Times.Once);
    }

    [Test]
    public void RegisterUser_ThrowWhenUserAlreadyExists()
    {
        _mockUserService.Setup(service => service.AddUser(It.IsAny<User>())).ThrowsAsync(new ConflictServiceException("TEST"));

        Assert.ThrowsAsync<ConflictServiceException>(async () => await _authenticationService.Register(TestData.ValidRegisterRequest));
    }

    [Test]
    public async Task RegisterUser_ValidReturnUserId()
    {
        _mockUserService.Setup(service => service.AddUser(It.IsAny<User>())).ReturnsAsync(TestData.ValidUser);

        UserAuthResponseDto response = await _authenticationService.Register(TestData.ValidRegisterRequest);
        Assert.That(response.UserId, Is.EqualTo(TestData.ValidUser.Id));
    }
}